/*
 * Jaio: Java API for libaio
 *
 * Author:
 * Jonas Pfefferle <jpf@zurich.ibm.com>
 *
 * Copyright (C) 2016, IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_jaio_NativeDispatcher */

#ifndef _Included_com_ibm_jaio_NativeDispatcher
#define _Included_com_ibm_jaio_NativeDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    io_setup
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_jaio_NativeDispatcher_io_1setup
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    io_submit
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_io_1submit
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    io_getevents
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_io_1getevents
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    io_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_jaio_NativeDispatcher_io_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_jaio_NativeDispatcher_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
