/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_jaio_NativeDispatcher */

#ifndef _Included_com_ibm_jaio_NativeDispatcher
#define _Included_com_ibm_jaio_NativeDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    io_setup
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_jaio_NativeDispatcher_io_1setup
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    io_submit
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_io_1submit
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    io_getevents
 * Signature: (JJJJJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_io_1getevents
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    io_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_jaio_NativeDispatcher_io_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    open
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_jaio_NativeDispatcher_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    o_direct
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_o_1direct
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    o_rdonly
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_o_1rdonly
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    o_wronly
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_o_1wronly
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    o_rdwr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_o_1rdwr
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    o_dsync
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_o_1dsync
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_jaio_NativeDispatcher
 * Method:    o_sync
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ibm_jaio_NativeDispatcher_o_1sync
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
